export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SAGA = 'AUTH_LOGOUT_SAGA';
export const AUTO_LOGIN ='AUTO_LOGIN';
export const CHECK_TIMEOUT = 'CHECK_TIMEOUT';

export const SAVE_CHECKLIST = 'SAVE_CHECKLIST';
export const SAVING_CHECKLIST_START = 'SAVING_CHECKLIST_START';
export const SAVING_CHECKLIST_SUCCESS = 'SAVING_CHECKLIST_SUCCESS';
export const SAVING_CHECKLIST_FAIL = 'SAVING_CHECKLIST_FAIL';

export const FETCH_CHECKLISTS_START = 'FETCH_CHECKLISTS_START';
export const FETCH_CHECKLISTS_SUCCESS = 'FETCH_CHECKLISTS_SUCCESS';
export const FETCH_CHECKLISTS_FAIL = 'FETCH_CHECKLISTS_FAIL';
export const FETCH_CHECKLISTS = 'FETCH_CHECKLISTT';