export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SAGA = 'AUTH_LOGOUT_SAGA';
export const AUTO_LOGIN ='AUTO_LOGIN';
export const CHECK_TIMEOUT = 'CHECK_TIMEOUT';

export const SAVE_CHECKLIST = 'SAVE_CHECKLIST';
export const SAVING_CHECKLIST_START = 'SAVING_CHECKLIST_START';
export const SAVING_CHECKLIST_SUCCESS = 'SAVING_CHECKLIST_SUCCESS';
export const SAVING_CHECKLIST_FAIL = 'SAVING_CHECKLIST_FAIL';

export const FETCH_CHECKLISTS_START = 'FETCH_CHECKLISTS_START';
export const FETCH_CHECKLISTS_SUCCESS = 'FETCH_CHECKLISTS_SUCCESS';
export const FETCH_CHECKLISTS_FAIL = 'FETCH_CHECKLISTS_FAIL';
export const FETCH_CHECKLISTS = 'FETCH_CHECKLISTT';

export const GET_CHECKLIST_BY_ID_START = 'GET_CHECKLIST_BY_ID_START';
export const GET_CHECKLIST_BY_ID_SUCCESS = 'GET_CHECKLIST_BY_ID_SUCCESS';
export const GET_CHECKLIST_BY_ID_FAIL = 'GET_CHECKLIST_BY_ID_FAIL';
export const GET_CHECKLIST_BY_ID = 'GET_CHECKLIST_BY_ID';

export const SET_CHECKLIST_TO_USE = 'SET_CHECKLIST_TO_USE';

export const SAVE_USED_CHECKLIST_START = 'SAVE_USED_CHECKLIST_START';
export const SAVE_USED_CHECKLIST_SUCCESS = 'SAVE_USED_CHECKLIST_SUCCESS';
export const SAVE_USED_CHECKLIST_FAIL = 'SAVE_USED_CHECKLIST_FAIL';
export const SAVE_USED_CHECKLIST = 'SAVE_USED_CHECKLIST';

export const FETCH_USED_CHECKLISTS = 'FETCH_USED_CHECKLISTS';
export const FETCH_USED_CHECKLISTS_START = 'FETCH_USED_CHECKLISTS_START';
export const FETCH_USED_CHECKLISTS_SUCCESS = 'FETCH_USED_CHECKLISTS_SUCCESS';
export const FETCH_USED_CHECKLISTS_FAIL = 'FETCH_USED_CHECKLISTS_FAIL';